/*
 * Copyright (C) 2026 ICDeC
 *
 * Driver library for the Texas Instruments ADS1118 SPI ADC - STM32 HAL port.
 *
 * This is a SEPARATE port from the PULPissimo version (../ads1118.h /
 * ../ads1118.c), created because the mentor asked to validate the driver
 * on STM32 hardware first (ADS1118 is not yet wired to the PULPissimo
 * board's SPI). The PULPissimo files are untouched.
 *
 * Public API is intentionally kept function-name-identical to the
 * PULPissimo version (ads1118_init, ads1118_read_battery_voltage, etc.)
 * since the two are compiled as separate projects/binaries (STM32CubeIDE
 * vs pulp-runtime Makefile) and never linked together, so there is no
 * symbol clash.
 *
 * Uses the project's real ads1118_regs.h.
 */
#ifndef __ADS1118_STM32_H__
#define __ADS1118_STM32_H__

#include <stdint.h>
#include "ads1118_regs.h"  /* MUX/PGA/DR constants, platform-agnostic */

/* Fallback in case ads1118_regs.h doesn't already define this (needed for
 * the B- channel of the differential battery measurement below). Matches
 * the ADS1118 datasheet MUX field encoding: 101 = AINP=AIN1, AINN=GND. */
#ifndef ADS1118_MUX_AIN1_GND
#define ADS1118_MUX_AIN1_GND 0x5000
#endif

/* Fallback for the IN+ (TP4056 charger input) channel. MUX field 110 =
 * AINP=AIN2, AINN=GND. */
#ifndef ADS1118_MUX_AIN2_GND
#define ADS1118_MUX_AIN2_GND 0x6000
#endif

/* Provided by the STM32 HAL (via CubeMX-generated main.h / stm32xxx_hal.h).
 * Only forward-declared here to avoid hard-coding a specific STM32 family
 * header - the actual HAL header is pulled in by whatever .c file
 * includes this one inside a real CubeIDE project. */
#include "main.h"  /* CubeMX-generated: brings in SPI_HandleTypeDef, GPIO_TypeDef, HAL types */

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Mean Filter Configuration
 * ============================================================================
 * ads1118_read_raw_filtered() / ads1118_read_battery_voltage_filtered()
 * mengambil ADS1118_FILTER_SAMPLE_COUNT sampel, membuang nilai terbesar dan
 * terkecil (masing-masing 1 sampel), lalu merata-ratakan sisanya.
 */
#define ADS1118_FILTER_SAMPLE_COUNT   12u  /**< Jumlah sampel mentah yang diambil */
#define ADS1118_FILTER_DISCARD_COUNT  2u   /**< Dibuang: 1 terbesar + 1 terkecil */
#define ADS1118_FILTER_AVG_COUNT      (ADS1118_FILTER_SAMPLE_COUNT - ADS1118_FILTER_DISCARD_COUNT) /**< 10 */

/* ============================================================================
 * SPI Retry Configuration
 * ============================================================================
 * Breadboard/kabel jumper kadang menyebabkan transaksi SPI sesekali gagal
 * (glitch fisik sesaat, bukan wiring salah total). ads1118_read_raw()
 * akan retry sampai ADS1118_SPI_RETRY_COUNT kali (dengan jeda
 * ADS1118_SPI_RETRY_DELAY_MS antar percobaan) sebelum benar-benar
 * menyerah dan mengembalikan ADS1118_ERR_SPI ke pemanggil.
 */
#define ADS1118_SPI_RETRY_COUNT     3u  /**< Jumlah percobaan (termasuk yang pertama) */
#define ADS1118_SPI_RETRY_DELAY_MS  1u  /**< Jeda antar percobaan, ms */

/* ============================================================================
 * Status Codes
 * ============================================================================ */

typedef enum {
    ADS1118_OK         = 0,   /**< Operation completed successfully */
    ADS1118_ERR_SPI    = -1, /**< SPI communication error (HAL_SPI_TransmitReceive failed) */
    ADS1118_ERR_NULL   = -2, /**< NULL pointer passed as argument */
    ADS1118_ERR_CONFIG = -3  /**< Invalid configuration / not initialized */
} ads1118_status_t;

/* ============================================================================
 * Configuration Structure
 * ============================================================================ */

typedef struct {
    SPI_HandleTypeDef *hspi;          /**< SPI handle generated by CubeMX (e.g. &hspi1).
                                            SPI Mode 1 (CPOL=Low, CPHA=2Edge) MUST be
                                            configured in CubeMX - it cannot be changed
                                            from this driver at runtime. */
    GPIO_TypeDef      *cs_port;       /**< GPIO port for the chip-select pin (e.g. GPIOA) */
    uint16_t           cs_pin;        /**< GPIO pin for chip-select (e.g. GPIO_PIN_4) */
    uint16_t           mux;           /**< Input multiplexer config for B+ (see ads1118_regs.h) */
    uint16_t           pga;           /**< Full-scale range / gain config (shared by B+ and B-) */
    uint16_t           data_rate;     /**< Conversion data rate config (shared by B+ and B-) */
    float              vdivider_ratio;/**< R2/(R1+R2) of the B+ voltage divider.
                                            Use 1.0f if B+ is wired directly to
                                            AIN0 with no divider. */

    /* -------------------------------------------------------------------
     * B- channel (added for chargers like TP4056 where B- is isolated
     * from system GND by the protection MOSFETs, so it can't be assumed
     * to sit at 0V - it must be measured too, against the SAME GND
     * reference as B+ (typically USB-/charger GND), and subtracted:
     *     battery_voltage = V(B+) - V(B-)
     * ------------------------------------------------------------------- */
    uint16_t           mux_bminus;         /**< MUX config for the B- channel.
                                                 Default: ADS1118_MUX_AIN1_GND
                                                 (single-ended AIN1 vs GND). */
    float               vdivider_ratio_bminus; /**< R2/(R1+R2) of the B- voltage
                                                 divider you added. Use 1.0f if
                                                 B- is wired directly to AIN1
                                                 with no divider. */

    /* -------------------------------------------------------------------
     * IN+ channel (TP4056 charger input voltage, e.g. USB 5V) - used
     * PURELY for charge detection, independent of the battery voltage
     * measurement above.
     * ------------------------------------------------------------------- */
    uint16_t           mux_inplus;         /**< MUX config for the IN+ channel.
                                                 Default: ADS1118_MUX_AIN2_GND
                                                 (single-ended AIN2 vs GND). */
    float               vdivider_ratio_inplus; /**< R2/(R1+R2) of the IN+ voltage
                                                 divider (IN+ is typically ~5V
                                                 from USB, so this almost always
                                                 NEEDS a divider to fit the PGA
                                                 range - do not leave at 1.0f
                                                 unless you've confirmed IN+
                                                 never exceeds your PGA's FS). */

    /* -------------------------------------------------------------------
     * Low-battery notification / charge detection
     * ------------------------------------------------------------------- */
    float              low_batt_threshold_v;     /**< battery_voltage below this
                                                        (V(B+) - V(B-)) triggers the
                                                        low-battery alert - but ONLY
                                                        while not charging. */
    float              charge_detect_threshold_v;/**< Simple threshold on V(IN+):
                                                        if V(IN+) is above this value,
                                                        the charger is considered
                                                        connected/charging (e.g. USB
                                                        5V present), and the
                                                        low-battery alert is suppressed.
                                                        Independent of battery voltage -
                                                        tune to sit comfortably between
                                                        your IN+ divider's "USB present"
                                                        and "USB absent" readings. */
} ads1118_config_t;

/* ============================================================================
 * API Functions (identical set to the PULPissimo version)
 * ============================================================================ */

/**
 * @brief Load a sensible default configuration.
 *
 * Default assumes: single-ended AIN0 vs GND for B+, PGA=+-4.096V (safety
 * margin above an expected ~2.1V at AIN0), 128SPS, and a 2:1 voltage
 * divider (vdivider_ratio=0.5). For B-: single-ended AIN1 vs GND,
 * vdivider_ratio_bminus=0.5 (placeholder - MUST match your actual B-
 * divider). For IN+ (charger input, e.g. USB 5V): single-ended AIN2 vs
 * GND, vdivider_ratio_inplus=0.5 (placeholder - MUST match your actual
 * IN+ divider; note IN+ is typically ~5V so almost always needs a
 * divider to fit within the PGA range). low_batt_threshold_v defaults
 * to 3.3V, charge_detect_threshold_v defaults to 3.0V (on V(IN+), both
 * illustrative - tune to your actual battery/charger behavior). hspi/
 * cs_port/cs_pin are left NULL/0 - the caller MUST fill these in before
 * calling ads1118_init(), since they depend on the specific CubeMX pin/
 * peripheral assignment of the board.
 */
ads1118_status_t ads1118_default_config(ads1118_config_t *cfg);

/**
 * @brief Initialize the ADS1118 driver (stores config; SPI peripheral
 *        itself must already be initialized by CubeMX/HAL_SPI_Init()).
 */
ads1118_status_t ads1118_init(const ads1118_config_t *cfg);

/**
 * @brief Trigger a single-shot conversion and read back the raw 16-bit
 *        two's-complement ADC code.
 *
 * Sequence: (1) trigger a new conversion, (2) wait the conversion time
 * estimated from the configured data rate (real timer via HAL_Delay),
 * (3) read out the result. This does NOT poll the config register's OS
 * "conversion done" bit - field testing showed some ADS1118 modules
 * (particularly low-cost/clone breakout boards) never report that bit
 * correctly even though they convert and update DATA normally, so
 * relying on it caused false failures on otherwise-working hardware.
 * The data-rate delay is the datasheet's own recommended minimum wait.
 */
ads1118_status_t ads1118_read_raw(int16_t *raw);

/**
 * @brief Read the battery voltage, compensating for the configured
 *        voltage divider ratio.
 */
ads1118_status_t ads1118_read_battery_voltage(float *voltage);

/**
 * @brief Trigger ADS1118_FILTER_SAMPLE_COUNT (12) single-shot conversions
 *        and return a filtered mean of the raw ADC code.
 *
 * Sorts the 12 raw samples, discards the single largest and single
 * smallest value (2 samples total), then averages the remaining 10
 * (ADS1118_FILTER_AVG_COUNT) samples. This rejects single-sample spikes
 * / outliers better than a plain mean.
 *
 * Each of the 12 samples comes from ads1118_read_raw() (delay-based,
 * see its docs). Spacing between samples follows automatically from the
 * configured data rate (e.g. ~10ms/sample at 128SPS, ~120ms total for
 * 12 samples) - if the data rate is changed later, the pacing changes
 * accordingly.
 *
 * @param[out] raw_filtered  Filtered mean, rounded to nearest int16_t.
 */
ads1118_status_t ads1118_read_raw_filtered(int16_t *raw_filtered);

/**
 * @brief Same as ads1118_read_battery_voltage(), but sourced from
 *        ads1118_read_raw_filtered() (12-sample mean filter, largest +
 *        smallest discarded) instead of a single raw reading.
 */
ads1118_status_t ads1118_read_battery_voltage_filtered(float *voltage);

/* ============================================================================
 * Differential B+/B- measurement (TP4056-style isolated B-), plus
 * independent IN+ charge detection
 * ============================================================================
 * For chargers (e.g. TP4056 + protection board) where B- is isolated from
 * system GND by the protection MOSFETs, true battery voltage can't be
 * measured as a single AIN0-vs-GND reading. Instead measure B+ and B-
 * separately (both referenced to the SAME GND, e.g. USB-/charger GND),
 * and subtract: battery_voltage = V(B+) - V(B-).
 *
 * Charge detection is measured SEPARATELY and independently via a third
 * channel, IN+ (the TP4056's charger input, e.g. USB 5V) - NOT derived
 * from the battery voltage at all, since IN+ directly reflects whether
 * a charger is physically plugged in (~5V when present, ~0V when not),
 * regardless of what state the battery itself is in.
 *
 * Each call here does a FULL 12-sample filtered read (see
 * ads1118_read_raw_filtered()) on ALL THREE channels (B+, B-, IN+), i.e.
 * 36 ADC conversions total - roughly triple the time of a single-channel
 * filtered read (e.g. ~360ms at the default 128SPS, not ~120ms).
 */

/**
 * @brief Read V(B+), V(B-), V(IN+) (each 12-sample filtered), compute
 * battery_voltage = V(B+) - V(B-), and derive charge/low-battery status.
 *
 * Charge detection: charging is considered active if V(IN+) is above
 * cfg.charge_detect_threshold_v (see ads1118_config_t docs - tune this to
 * sit comfortably between your IN+ divider's "USB present" and "USB
 * absent" readings on your specific board).
 *
 * Low-battery alert: set only if battery_voltage is below
 * cfg.low_batt_threshold_v AND charging is NOT active (i.e. it clears
 * automatically the moment the charger is plugged in, per your request).
 *
 * @param[out] battery_voltage  V(B+) - V(B-), may be NULL if not needed.
 * @param[out] v_bminus         V(B-) alone, may be NULL if not needed.
 * @param[out] v_inplus         V(IN+) alone, may be NULL if not needed
 *                               (useful for tuning charge_detect_threshold_v).
 * @param[out] is_charging      1 if charging detected, 0 otherwise. May be NULL.
 * @param[out] low_battery_alert 1 if alert should be shown, 0 otherwise. May be NULL.
 */
ads1118_status_t ads1118_read_battery_status(float *battery_voltage,
                                              float *v_bminus,
                                              float *v_inplus,
                                              int *is_charging,
                                              int *low_battery_alert);

/**
 * @brief Reset driver state (does not de-init the SPI peripheral itself -
 *        that remains owned by CubeMX/HAL, same as it was initialized
 *        outside this driver).
 */
ads1118_status_t ads1118_deinit(void);

/**
 * @brief DEBUG ONLY - reports the driver's internal "initialized" flag
 * and the exact hspi/cs_port pointer values it currently holds.
 *
 * Call this from anywhere (e.g. right before ads1118_read_raw_filtered()
 * in the main loop) to check, in real time, whether THIS build of the
 * driver still believes it's initialized. If ads1118_init() printed
 * success at boot but this later reports initialized=0, that's strong
 * evidence of a stale/mismatched build (old .o file linked in) rather
 * than a real runtime bug - do a full Project > Clean + rebuild.
 */
void ads1118_debug_print_state(void);

/* ============================================================================
 * Pure helper functions (exposed for direct unit testing, no hardware access)
 * ============================================================================ */

uint16_t ads1118_encode_config(uint16_t mux, uint16_t pga, uint16_t data_rate);
float    ads1118_raw_to_voltage(int16_t raw, uint16_t pga);

#ifdef __cplusplus
}
#endif

#endif /* __ADS1118_STM32_H__ */
