PULP_APP = test
PULP_APP_C_SRCS = \
	main.c \
	tests/test_pixel.c \
	tests/test_line.c \
	tests/test_kotak.c \
	tests/test_tangga.c \
	tests/test_papancatur.c \
	tests/test_text.c \
	tests/test_circle.c \
	GUI/test/test_gui_textbox.c \
	GUI/test/test_gui_button.c \
	GUI/test/test_gui_checkbox.c \
	GUI/test/test_gui_progress.c \
	GUI/test/test_gui_input.c \
	GUI/demo.c \
	GUI/ui_layer/ui_manager.c \
	GUI/ui_layer/ui_oxygen.c \
	GUI/ui_layer/ui_activity.c \
	GUI/ui_layer/ui_stepcount.c \
	GUI/ui_layer/ui_alarm.c \
	font/font5x7.c \
	oled.c \
	GUI/gui_port.c \
	GUI/gesture.c \
	GUI/ugui/ugui.c \
	GUI/ugui/fitur/ugui_button.c \
	GUI/ugui/fitur/ugui_checkbox.c \
	GUI/ugui/fitur/ugui_image.c \
	GUI/ugui/fitur/ugui_progress.c \
	GUI/ugui/fitur/ugui_textbox.c \
	GUI/ugui/fitur/Fonts/font_6x10.c

PULP_CFLAGS = -Os -flto -g -I. -IGUI -IGUI/ugui -IGUI/ugui/fitur

include $(PULPRT_HOME)/rules/pulp.mk

