PULP_APP = test_lis3dhtr
PULP_APP_C_SRCS = test_lis3dhtr.c lis3dhtr.c
PULP_CFLAGS = -O3 -g
PULP_ARCH_CFLAGS ?=  -march=rv32imcxpulpv2
PULP_ARCH_C_LDFLAGS ?=  -march=rv32imcxpulpv2
include $(PULPRT_HOME)/rules/pulp.mk
