PULP_APP        = test
PULP_APP_C_SRCS = test.c \
                  step_counter.c \
                  ../../sensors/lis3dhtr/lis3dhtr.c \
                  ../../sensors/DS1307/rtc.c

PULP_CFLAGS     = -O3 -g \
                  -I../../sensors/lis3dhtr \
                  -I../../sensors/DS1307

include $(PULPRT_HOME)/rules/pulp.mk